### ISSUE TITLE
Regarding the documentation present on community tutorials

### ISSUE THREAD

**Issue by Ha25hit** [GoogleCloudPlatform/community#1040]
Please provide the proper documentation of how do you connect the prometheus and grafana with core iot and pubsub as tutorial you posted was not clear the purpose so re-post it with more detailed information

**Comment by ToddKopriva** [comment]
@Ha25hit , could you give more details about the problems that you found with this tutorial?
https://cloud.google.com/community/tutorials/cloud-iot-prometheus-monitoring

@ptone , I'm tagging you so that you can see this request about a tutorial that you submitted.

**Comment by Ha25hit** [comment]
Yes ... The  thing is that we are not able to connect pubsub service to
kubernetes cluster where we deployed Prometheus. No proper way is shown in
that document.
The document suggest that we should convert the incoming data into some
metrics ... For this a went to the promiot GitHub link there also no
documents how do I convert data for Prometheus and send over mqtt

I'm familiar with Python but not with GO .. the architecture shown in that
document is Clear but these steps i personally found issues ..

I'm doing some hands-on using gcp core IoT, pubsub, kubernetes for sensor
analytics and alert generation. I want all these things at real time. Let
me know what you think..and how to proceed further..

Thanks
Harshit

**Comment by ToddKopriva** [comment]
Thanks for the details of the problems. We'll have a look.

**Comment by ptone** [comment]
Thanks for the report. The focus of the tutorial is on the integration of a pod that exposes iot style data, and how that is scraped into prometheus, and how to right example queries in prometheus query language.

The architecture provided for how data gets from device to the pod is only provided as a pattern, not an implementation. The pattern could be fulfilled in python or go.

A rough implementation of the pattern in golang is provided outside of the tutorial in the promiot package.

https://github.com/ptone/promiot/blob/master/example-receiver/main.go

shows how the receiver unpacks data on from a cloud pubsub subscription and publishes it in the standard prometheus scraper target form, and could be run on the pod instead of the simulator.

I can add some qualifying language to the later part of the tutorial if you think this could be more clear.

-P

**Comment by ToddKopriva** [comment]
Thanks for the response, @ptone .

I'm going to close this issue as resolved with that information. @Ha25hit , you are still welcome to ask questions if you need more help.

If you have more involved questions, I recommend coming to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.
