### ISSUE TITLE
Managing Symfony 5 cache in GAE with Memcache 

### ISSUE THREAD

**Issue by Sethbass** [GoogleCloudPlatform/community#1137]
Hello,

I found this tutorial which is a great starting point for Symfony latest versions : 
https://cloud.google.com/community/tutorials/run-symfony-on-appengine-standard?hl=fr

In the first version of the tutorial we had a starter project : 
https://github.com/GoogleCloudPlatform/appengine-symfony-starter-project

This project was leveraging GAE Memcache system which I think is great to improve the application performances. 

The content of the code in the starter projet is really outdated as many thing have changed on Symfony side. Despite spending hours on it I was not able to make it work.

If anybody can help on this matter, I would be more than grateful :) 

Thanks a lot

Sebastien

**Comment by bshaffer** [comment]
The `appengine-symfony-starter-project` has been removed in favor of the tutorial found [here](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/symfony-framework), which is the same code used in the community tutorial you mention.

The GAE Memcache service is not available for PHP 7.2 on App Engine. A memcache service *does* exist, and it uses [MemoryStore](https://cloud.google.com/memorystore/docs/redis) and Cloud Connect. You can see a sample of how to use it [here](https://github.com/GoogleCloudPlatform/php-docs-samples/tree/master/appengine/php72/memorystore). It's trickier and more expensive to set up than the previous GAE Memcache service was, which is why in the tutorial above we use per-instance filecaching instead. 

If you think it'd be useful, we could potentially add to the tutorial an example of using Memorystore for Symfony caching. But the old starter project is completely defunct, and none of it will apply to the new PHP 7.2/7.3 runtimes.

**Comment by Sethbass** [comment]
Hi @bshaffer , 

Thanks a lot for responding, I have been through the documentation and the files you shared in Github and I think that a tutorial would be more than welcome here. Using symfony on premise we were able to set the cache folders with the appropriate read/write permissions, but on a serverless instance this is not possible and this is impacting hugely the application performances. Redis seems to be a solution widely used these days so I think we can all benefits from this :) 

Actually, I have many applications running with Symfony on GAE and so far I had 2 pain points:
* the cache
* the emails (which I solved using Mailgun but there are rooms for improvement here as the mail solution from Google Cloud is also not working with PHP 7.x)

So, if we have this tutorial we will be able to move all the applications that are still running on premise today :)

If you need a Guinea pig to test this tutorial, I would be more than happy to help and to give a feedback.

Thanks a lot for your time,

Sebastien

**Comment by bshaffer** [comment]
Yes, you are right! The old tutorial uses the App Engine Mail service, which has been removed in the "2nd gen" App Engine standard runtimes (e.g. PHP 7.2) along with the Memcache service. The [migration guide](https://cloud.google.com/appengine/docs/standard/php7/php-differences#migrating_from_the_app_engine_php_sdk) outlines the services that have been removed, and the new "recommended way". 

I'll consider adding to the tutorial how to implement caching via Memorystore and email via Mailgun/Mailjet. Great idea, and I'd definitely love to use you as a guinnea pig :D

**Comment by Sethbass** [comment]
@bshaffer , I made a pull request for the email tutorial. If you can help with the cache tutorial it would be perfect ;) I also have a bit of experience with the Storage and Symfony using Vich uploader and Gaufrette, if you think this could be useful to anyone I can try to enrich the README.

**Comment by bshaffer** [comment]
@Sethbass I reviewed your PR. It looks great, thank you!
