### ISSUE TITLE
Issue with tutorials/getting-started-on-gcp-with-terraform/index.md

### ISSUE THREAD

**Issue by rohit-asave** [GoogleCloudPlatform/community#1139]
Issue Description

I was going through the tutorial and I found that one step was missing in the tutorial for starting the Flask Application.

Please update with these two commands.

env FLASK_APP=app.py flask run

And another one for verifying with curl:

curl -X GET http://127.0.0.1:5000/

**Comment by ToddKopriva** [comment]
@rohit-asave : Thanks for the report. If you know how to fix the tutorial, you are welcome to submit a pull request with the fix, which we'll review.

@chrisst : Could you have a look at this issue regarding a tutorial that you contributed?
https://cloud.google.com/community/tutorials/getting-started-on-gcp-with-terraform

**Comment by chrisst** [comment]
@rohit-asave thanks for the feedback! I'll add the syntax for the curl command. 

However the command to run the flask server for the current version of flask does encourage using `flask run` but older versions do not support that. Since the current command is still compatible with older and newer versions of flask I'm going to keep it in the doc.
