### ISSUE TITLE
 Issue with tutorials/docker-compose-on-container-optimized-os CTRL+C doesn't work

### ISSUE THREAD

**Issue by Krzysiaczek-at-MasAndPas** [GoogleCloudPlatform/community#1455]
Hi

I followed the instruction. It works with only difference that I had to update the version number to the recent one 1.27.4

The only problem I found is that CTRL+C doesn't work as on localhost to stop containers initiated with docker-compose up.

Thanks

**Comment by Krzysiaczek-at-MasAndPas** [comment]
When I login to another instance of the console I can go to the same folder and stop it by running docker-compose stop

**Comment by ToddKopriva** [comment]
Thanks for the report. I'll take a look.

**Comment by MonksterFX** [comment]
Same Issue over here with Version 1.27.4

**Comment by malcolmredheron** [comment]
As far as I can tell so far, I fixed this by adding `-it` to the alias, yielding the following. Notably, this works with `docker-compose up`, so that the first control-c stops the processes gently and the second one more forcefully, as usual.

```
alias docker-compose='docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -w="$PWD" \
    -it \
    docker/compose:1.28.4'
```

**Comment by ToddKopriva** [comment]
Thanks for that additional information, @malcolmredheron .

**Comment by malcolmredheron** [comment]
The problem with adding `-it` is that it seems to prevent interaction with the job I run. For example, I can pipe something to stdin without `-it` but not with it.

Also worth noting: setting this up as an alias means that you can't (or can't easily?) call it from a script. I made docker-compose a script in my path instead.

I get that there are probably GCE tools that I should be using instead of docker-compose, but it's disappointing how much time I've spent trying to get this to work.

**Comment by ToddKopriva** [comment]
This document has been moved to the archive.
