### ISSUE TITLE
Issue with tutorials/cloud-run-local-dev-docker-compose/index.md

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/community#1506]
The instructions in the tutorial use an older version of the Cloud SQL proxy (1.14 -> 1.17). It needs to be updated and add instructions for specifying the nonroot user.

See this report:
https://github.com/GoogleCloudPlatform/cloudsql-proxy/issues/430

**Comment by grayside** [comment]
I've begun looking into this, and so far identified a few changes to make:

1. Switch from Cloud SQL Proxy 1.14 to 1.19.1. Unfortunately I don't see a `1.19` tag to follow so the tutorial will not automatically incorporate patch releases.

2. Mount the service account key file inside the `/tmp` directory instead of a user home directory.

3. Override the Cloud SQL Proxy to run as root. This tutorial uses the approach of a shared volume between containers, so the non-root permissions are complicated and less valuable given the local execution.

Making those changes is principally:

```diff
  sql_proxy:
-   image: gcr.io/cloudsql-docker/gce-proxy:1.14
+   image: gcr.io/cloudsql-docker/gce-proxy:1.19.1
    command:
      - "/cloud_sql_proxy"
      - "-dir=/cloudsql"
      - "-instances=${CLOUDSQL_CONNECTION_NAME}"
-     - "-credential_file=/root/keys/keyfile.json"
+     - "-credential_file=/tmp/keys/keyfile.json"
+   # Allow the container to bind to the unix socket.
+   user: root
    volumes:
-     - ${GCP_KEY_PATH}:/root/keys/keyfile.json:ro
+     - ${GCP_KEY_PATH}:/tmp/keys/keyfile.json:ro
      - cloudsql:/cloudsql
```

I am using https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/run/idp-sql to test this, and I'm running into an error:

```
connect ENOTDIR /cloudsql/[CONNECTION_NAME]/.s.PGSQL.5432
```

Once I work through this and follow-up issues I'll send a PR.

**Comment by ToddKopriva** [comment]
Thanks, @grayside .

**Comment by grayside** [comment]
Brief follow-up on that error: I was trying to use a Postgres library to query a MySQL database.

**Comment by ToddKopriva** [comment]
Thanks for the clarification.
