### ISSUE TITLE
tutorials/create-a-self-deleting-virtual-machine.md - Windows how-to request

### ISSUE THREAD

**Issue by mattia-molinario** [GoogleCloudPlatform/community#1517]
How can i achieve a similar result with a Windows VM?
I'd like to auto-delete the Windows VM after a fixed time from first user login.

**Comment by engelke** [comment]
I'm not an experienced Windows Server administrator, but the steps should be nearly identical. Instead of creating a bash script, you'll need to create a .cmd, .bat, or .ps1 script. You'll set the custom metadata using one of the Windows script names instead of startup-script (see https://cloud.google.com/compute/docs/startupscript#providing_a_startup_script_for_windows_instances). The gcloud and curl tools should already be installed. Instead of using `sleep` to wait for an hour (or however long is desired) you'd use a Windows-specific command, such as start-sleep for PowerShell.

**Comment by ToddKopriva** [comment]
Thanks for the answer, @engelke .
