### ISSUE TITLE
Issue with tutorials/docker-compose-on-container-optimized-os.md

### ISSUE THREAD

**Issue by JetsonDavis** [GoogleCloudPlatform/community#1707]
This tutorial doesn't seem to work anymore!

**Comment by ToddKopriva** [comment]
@tswast , can you have a look at this?

@JetsonDavis , can you give more details about exactly what issues you encountered?

**Comment by JetsonDavis** [comment]
Yes!

I’m really struggling to find current docs about how to set up docker & docker-compose on a Compute.

I follow the instructions up to the ‘docker run…’ command.  I get this on my ssh session:

Starting dockercloud-hello-world_helloworld_1 … done

I click on the IP listed on the dashboard and get ‘unable to connect’

Thanks

**Comment by JetsonDavis** [comment]
What would really be great if there was a doc that can take me from setting up a VM to being able to run docker-compose with a project I have on both DockerHub and (I think) on your one, I think it's called Container Registry.

**Comment by tswast** [comment]
I don't have a good sense for the importance of docker-compose materials, but it's been well over two years since this post was first written, which is the support duration of an LTS container optimized OS image https://cloud.google.com/container-optimized-os/docs/concepts/versioning As such, I suspect there have been some breaking changes since I wrote these instructions.

I do not have time to revisit this tutorial, so unless we get a community contribution to fix it, we may need to archive this article.

**Comment by ToddKopriva** [comment]
Thanks, @tswast .

I'll go ahead and move this to the archive and include a link to this issue report in that pull request. Then, anyone who wants to update this can see what the issues are and can move the document back and get it re-published.

**Comment by ToddKopriva** [comment]
Thanks for report, @JetsonDavis .
