### ISSUE TITLE
Is the URL map creation step missing?

### ISSUE THREAD

**Issue by dgalmeida** [GoogleCloudPlatform/community#1798]
Hi, on [tutorials/securing-gcs-static-website](https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/securing-gcs-static-website/index.md#create-the-url-map-and-configure-forwarding-rules) I think the creation of the file web-map-http.yaml wasn't described. How use 'sed' replace into unknown file? We should use `gcloud compute url-maps create` and `gcloud describe` command to download the url map file and then 'sed' to replace, shouldn't we? Or did I miss something?

**Comment by xiangshen-dk** [comment]
You can find the web-map-http.yaml in the repo at: https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/securing-gcs-static-website/flask_login/web-map-http.yaml

The tutorial assumes you are already in the directory so that you can use 'sed' with the file. 

If you want to read more about URL maps, you can go to https://cloud.google.com/load-balancing/docs/url-map-concepts
