### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-cisco-asr/index.md

### ISSUE THREAD

**Issue by brisoper** [GoogleCloudPlatform/community#2115]
Issue Description
This tutorial accommodates NAT-T, but in order for a Cisco ASR behind NAT to work, the ASR will need to have:
```
crypto ikev2 profile VPN_SCALE_TEST_IKEV2_PROFILE
 identity local address <public ip of ASR>
```
Cloud VPN requires that the IDi the initiator submits match the public IP address it is using (Source: https://cloud.google.com/network-connectivity/docs/vpn/support/troubleshooting#gateways_behind_nat).

**Comment by dariush-a** [comment]
@ashishverm 
I already looked at this issue with Brian.
Brian tested the code on Cisco CSR since he doesn't have access to an ASR. We believe the fix should work on Cisco ASR too but we can't be 100% sure unless we can get our hands on an ASR.
@ashishverm Can we get access to a Cisco ASR?

We will make the changes to the tutorial and let you know.

**Comment by dariush-a** [comment]
@brisoper will be updating the tutorial:
`crypto ikev2 profile VPN_SCALE_TEST_IKEV2_PROFILE
 identity local address <public ip of ASR>`

**Comment by ToddKopriva** [comment]
This unmaintained document has been moved to the archive.

https://github.com/GoogleCloudPlatform/community/pull/2426
