### ISSUE TITLE
Issue with tutorials/using-cloud-vpn-with-strongswan/index.md

### ISSUE THREAD

**Issue by nomadturk** [GoogleCloudPlatform/community#2199]
Issue Description

The strongswan package comes with farp package by default.
Combined with the VTI usage, this creates a lot of problems.  

Check:
https://bugzilla.redhat.com/show_bug.cgi?id=1488421

This tutorial needs to be updated to make sure users disable farp package, or at least it should warn against possible network problems that originates from the use of this package.

```
/etc/strongswan.d/charon/farp.conf
```
must be edited and 

```
farp {

    # Whether to load the plugin. Can also be an integer to increase the
    # priority of this plugin.
    load = yes
}
```
should be changed to 

```
farp {

    # Whether to load the plugin. Can also be an integer to increase the
    # priority of this plugin.
    load = no
}
```

Otherwise it creates proxy arp issues and it hijacks other users IP space.

Additionally, we need to update ```/var/lib/strongswan/ipsec-vti.sh``` to make sure sysctl also blocks proxy arp.
```
        # Disable Proxy ARP on all interfaces
        sysctl -w net.ipv4.conf.all.proxy_arp = 0

        # Disable Proxy ARP on the new interface
        sysctl -w net.ipv4.conf.${VTI_IF}.proxy_arp=0
```

This was a costly experience for me.
Both datacenters suspended my servers because this Strongswan FARP package was trying to route all traffic through it and thus, hijacking other users IP space in a way.

**Comment by ToddKopriva** [comment]
Thanks for the report, @nomadturk .

@Civil , could you take a look at this request for an update for a document that you contributed?

**Comment by Civil** [comment]
@ToddKopriva I'm no longer TSE within Cloud Support, so while the suggestions seems legit, I can't possibly verify that it actually works. I think that we should find someone within current support org (SME on Cloud VPN maybe?) who would be responsible for updating documentation.

Because at least for modern StrongSwan versions, documentation should be updated to utilize XFRM but that comes with a lot of testing that needs to be done and for which I don't even have access (and I'm not talking about time here :) )

**Comment by ToddKopriva** [comment]
Thanks, @Civil .

**Comment by jschneider11** [comment]
+Severine Tymon ***@***.***>

FYI, Severine,  in case you know which VPN SME can help Todd.

**Comment by ToddKopriva** [comment]
moved unmaintained tutorial to archive

https://github.com/GoogleCloudPlatform/community/pull/2425
