### ISSUE TITLE
Issue with tutorials/securing-gcs-static-website/index.md

### ISSUE THREAD

**Issue by jameswjr** [GoogleCloudPlatform/community#2219]
I am using this to secure some static content. It only works from an incognito window. If I try it from a regular browser window, I am continually met with "you have already logged in" when I try to browse the site.

**Comment by xiangshen-dk** [comment]
This is a known issue with this solution - if multiple cookies are present in the header, the CDN cookie needs to be the first one in the header. Unfortunately, due to a current limitation of the urlmaps, there is no guarantee for the CDN cookie to take precedence. One workaround is to use a longer path for the order. You can find an example at: https://github.com/xiangshen-dk/securing-gcs-static-assets-iap:

```
Important: The path is needed here to make sure the CDN signed cookie will be the first in the cookie header string. It takes advantage of the fact that most browsers will sort the cookies from the longest path to the shortest path.
```

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
