### ISSUE TITLE
kubernetes-engine-customize-fluentbit tutorial and supported fluentbit version/features

### ISSUE THREAD

**Issue by Vincehood** [GoogleCloudPlatform/community#2332]
Hello,
the https://github.com/GoogleCloudPlatform/community/tree/master/tutorials/kubernetes-engine-customize-fluentbit tutorial:
-deploys fluentbit version 1.9.2 while the latest released fluentbit version at time of writing this message is 2.0.9
-uses one fluentbit input only (tail)

I therefore wonder about the following:
- does Cloud Operations for GKE always always support the latest version of Fluentbit?
- does Cloud Operations for GKE support other Fluentbit inputs such as TCP, HTTP, Forward...as long as Fluentbit stackdriver output is used?

If so, could the above be updated/mentioned in the tutorial?
Thanks
/Vincent

**Comment by ToddKopriva** [comment]
@xiangshen-dk , could you have a look at these questions about a tutorial that you contributed?

**Comment by xiangshen-dk** [comment]
@Vincehood 

By default, GKE is using FluentBit. The current latest version (2.0.9) works with this solution. In the foreseeable future, GKE should be able to support the latest version of FluentBit. However, there is no guarantee that the latest version of FluentBit will be supported right away or any version will work unconditionally (a version could be skipped due to a flaw or vulnerability, for example). 

When you use FluentBit, the inputs don't matter as long as you configure the output for cloud logging.

**Comment by ToddKopriva** [comment]
Thanks for the answers, @xiangshen-dk .
