### ISSUE TITLE
Issue with tutorials/serverless-vpc-access-private-mongodb-atlas/index.md

### ISSUE THREAD

**Issue by oelsayed40** [GoogleCloudPlatform/community#2391]
I've followed this tutorial to the letter and continue to get an error connecting to mongoDB from my cloud function. There is also some conflicting information in here (e.g. the connection string), but I've tried many different variants. I've temporarily whitelisted all IP and successfully connected to mongo doing this and the connection came from a different one setup in my serverless VPC. Any suggestions on what the issue could be?

**Comment by ToddKopriva** [comment]
@russStarr , could you take a look at this issue regarding a document that you contributed?

**Comment by russStarr** [comment]
@oelsayed40 for the connection string, were you able to get clarity from [MongoDB's doc](https://www.mongodb.com/docs/atlas/reference/faq/connection-changes/#std-label-connstring-private)?

When you say the connection came from a different one, can you elaborate? A different IP or subnet maybe? If the address was public instead of private, that could indicate that your Cloud Function may not be properly mapped to the serverless VPC connector. Did you get any error messages throughout the process?

If you have trouble using this design, you might consider looking at the [Private Service Connect](https://www.mongodb.com/docs/atlas/security-private-endpoint/) option for Mongo. It would still need the Serverless VPC connector but the PSC is more flexible than VPC peering.

**Comment by oelsayed40** [comment]
Yeah when I whitelist all IPs, the connection to mongo is coming from a public GCP IP address. I'm getting no error messages and followed the instructions. Perhaps we could troubleshoot offline?

**Comment by ToddKopriva** [comment]
This publishing system is being shut down, and documents that have previously been published through this system are being moved to the `/archived` folder of this repository and are no longer being maintained.
