### ISSUE TITLE
Laravel 5.5 on Google Cloud Engine

### ISSUE THREAD

**Issue by bmunyoki** [GoogleCloudPlatform/community#351]
I am running Laravel 5.5 on GAE with a MySQL instance running database. I want to be able to run database migrations after every build. I have added command "php artisan migrate" on post-install-cmd in composer.json but it does not seem to work. 
`"post-install-cmd": [
    		"chmod -R 755 bootstrap\/cache",
            "php artisan migrate",
    		"php artisan cache:clear"
	    ]`
The build log shows command running but looks like down there there is command cancelled. 
![cancelled](https://user-images.githubusercontent.com/22376891/35198625-18d864e0-fefa-11e7-9152-55a3c10dd105.png)

What could be the issue? How can I run migration after every build? Any help will be appreciated.

**Comment by tmatsuo** [comment]
@bmunyoki 

Unfortunately, during the build phase, the CloudSQL connection is not available.

First, remove `php artisan migrate` from the `post-install-cmd`, and try the following after the deployment(replace YOUR_VERSION with the actual version):

```
composer require --dev google/cloud-tools
vendor/bin/flex_exec run -t YOUR_VERSION -- php artisan migrate
```

Let me know if it doesn't work for you.

**Comment by tmatsuo** [comment]
Closing, feel free to re-open

**Comment by lpzdvd-packlink** [comment]
@tmatsuo 

*Unfortunately, during the build phase, the CloudSQL connection is not available.*

That's why I'm only allowed to execute a migrate command from app container *after* a deployment.

Definitely it should be in the PHP docs regarding App Engine since I've read a lot of articles and issues trying to use migrate in `gloud app deploy` commands. It was very strange because cloudsql proxy container logs stated that it was ready to accept connections but none was ever made. app deploy command throwed **SQLSTATE[HY000] [2002] No such file or directory** errors.

Really tricky anyway.
