### ISSUE TITLE
Performance issue with swagger in GAE standard/flex environment for spring-boot application

### ISSUE THREAD

**Issue by vijayakumar-psg587** [GoogleCloudPlatform/community#578]
I Implemented springfox-swagger in a spring boot application. The below is the configuration used in pom.xml.

```
                <dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger2</artifactId>
			<version>2.9.2</version>
		</dependency>
		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-swagger-ui</artifactId>
			<version>2.9.2</version>
		</dependency>

		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-bean-validators</artifactId>
			<version>2.9.2</version>
		</dependency>
```

And i have nearly 10 service endpoints defined in controller class. When i access swagger-ui.html in local, it's working fine and loading very fastly (Approximately 5 secs).

The same application had deployed to GAE standard/flex environment. But when i hit swagger-ui URL it is taking more time to load (Approximately 1-2 mins).. which leads to a performance issue.

Anybody can help me in this issue? Thanks.

**Comment by ToddKopriva** [comment]
The Issues section of this community tutorials GitHub repository is not the best place to get such questions answered.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

I'm going to close this issue, since it doesn't seem to directly apply to any of the tutorials in this repo. If I misunderstood, and your issue does in fact relate to one of the tutorials in this repo, go ahead and re-open the issue and give us more detail about the document with which you're encountering problems.
