### ISSUE TITLE
Issue with docker-compose-on-container-optimized-os

### ISSUE THREAD

**Issue by ayoubbargach** [GoogleCloudPlatform/community#583]
Hi !
Hi have the following error executing the docker run command : 

Error response from daemon: error while creating mount source path '/rootfs/home/bargachayoub/developer-edition/configs/core.ini': mkdir /rootfs: read-only file system

Same as here : https://stackoverflow.com/questions/46174297/running-docker-compose-inside-a-google-cloud-engine

there is any workaround ?

**Comment by ToddKopriva** [comment]
@tswast , could you take a look at this issue regarding a tutorial that you contributed?

**Comment by tswast** [comment]
Container-optimized OS mounts most paths as read-only. See: https://cloud.google.com/container-optimized-os/docs/concepts/disks-and-filesystem

The `/home` directory is writable, though.

I forget why I used `/rootfs/$PWD` instead of `$PWD` in https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os Maybe @ahmetb remembers from reviewing the PR?

**Comment by ricfri** [comment]
Had the same error and it works for me without the '/rootfs/' part:
`
docker run \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$PWD:$PWD" \
    -w="$PWD" \
    docker/compose:1.13.0 up
`

**Comment by ToddKopriva** [comment]
Thanks for the fix, Tim.
