### ISSUE TITLE
Issue with installing-mender-management-server

### ISSUE THREAD

**Issue by jakerye** [GoogleCloudPlatform/community#628]
I am unable to access the mender management demo server after deploying it on the compute engine. I expected to see the ERR_CERT_AUTHORITY_INVALID error, be able to dismiss it and access the site but instead I see the ERR_CONNECTION_TIMED_OUT error.

To reproduce, here is the tutorial I am following: https://cloud.google.com/community/tutorials/cloud-iot-mender-ota

**Comment by olilogic77** [comment]
I found the same issue and believe its because the startup script isn't executing in this line:
gcloud beta compute --project $PROJECT instances create "mender-ota-demo" --zone "us-central1-c" --machine-type "n1-standard-2" --subnet "default" --maintenance-policy "MIGRATE" --scopes "https://www.googleapis.com/auth/cloud-platform" --metadata=startup-script-url=https://raw.githubusercontent.com/GoogleCloudPlatform/community/master/tutorials/cloud-iot-mender-ota/server/mender_server_install.sh --min-cpu-platform "Automatic" --tags "https-server" --image "ubuntu-1604-xenial-v20180814" --image-project "ubuntu-os-cloud" --boot-disk-size "10" --boot-disk-type "pd-standard" --boot-disk-device-name "mender-ota-demo"

I initially thought that it was the '=' after the --metadata that was causing the issue, however removing that '=' didn't fix it.

Then, I logged in via ssh to the compute instance and ran:
sudo su -c "bash <(curl -s https://raw.githubusercontent.com/GoogleCloudPlatform/community/master/tutorials/cloud-iot-mender-ota/server/mender_server_install.sh)"

which installed the mender-server, however finished with:
writing RSA key
All Mender Server keys and certificates have been generated in directory /home/darren/mender-server/production/keys-generated.
Please include them in your docker compose and device builds.
For more information please see https://docs.mender.io/Administration/Certificates-and-keys.
[my-production-setup fc608f1] production: adding generated keys and certificates
 7 files changed, 132 insertions(+)
 create mode 100644 production/keys-generated/certs/api-gateway/cert.crt
 create mode 100644 production/keys-generated/certs/api-gateway/private.key
 create mode 100644 production/keys-generated/certs/server.crt
 create mode 100644 production/keys-generated/certs/storage-proxy/cert.crt
 create mode 100644 production/keys-generated/certs/storage-proxy/private.key
 create mode 100644 production/keys-generated/keys/deviceauth/private.key
 create mode 100644 production/keys-generated/keys/useradm/private.key
mender-artifacts
mender-deployments-db
mender-useradm-db
mender-inventory-db
mender-deviceadm-db
mender-deviceauth-db
mender-elasticsearch-db
mender-redis-db
/var/lib/docker/volumes/mender-artifacts/_data
On branch my-production-setup
nothing to commit, working directory clean
ERROR: Actual version is empty (hint: is it installed, or version format change?).
ERROR: Docker Engine must be on version 1.11 or larger, but found version 1. installed.
DOCKER_ENGINE_VERSION_STRING=Server Version: 18.09.1
ERROR: Actual version is empty (hint: is it installed, or version format change?).
ERROR: Docker Engine must be on version 1.11 or larger, but found version 1. installed.
DOCKER_ENGINE_VERSION_STRING=Server Version: 18.09.1
Copying file://keys-generated/certs/server.crt [Content-Type=application/x-x509-ca-cert]...
/ [1 files][  1.2 KiB/  1.2 KiB]                                                
Operation completed over 1 objects/1.2 KiB.  

I then went into the mender-engine directory and tried 'bash up' but it returned the same docker error.

Note that I'm pretty noob so I don't know if I'm doing the right thing :)

**Comment by Kcr19** [comment]
@olilogic77 - Mender server installation depends on the mender_server_install script - https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/cloud-iot-mender-ota/server/mender_server_install.sh and failing due to some changes to the Mender Integration repo from Mender team around docker version check. 

I have updated that script and issued a PR as fix to #628 but for now use this below command from the Google Cloud shell or terminal under "Installing Mender Management Server" section - [(https://github.com/GoogleCloudPlatform/community/blob/master/tutorials/cloud-iot-mender-ota/index.md#installing-mender-management-server)]

gcloud beta compute --project $PROJECT instances create "mender-ota-demo" --zone "us-central1-c" --machine-type "n1-standard-2" --subnet "default" --maintenance-policy "MIGRATE" --scopes "https://www.googleapis.com/auth/cloud-platform" --metadata=startup-script-url=https://raw.githubusercontent.com/Kcr19/community/master/tutorials/cloud-iot-mender-ota/server/mender_server_install.sh --min-cpu-platform "Automatic" --tags "https-server" --image "ubuntu-1604-xenial-v20180814" --image-project "ubuntu-os-cloud" --boot-disk-size "10" --boot-disk-type "pd-standard" --boot-disk-device-name "mend
er-ota-demo"
