### ISSUE TITLE
Issue with mongodb-atlas-appengineflex-nodejs-app

### ISSUE THREAD

**Issue by TomyJaya** [GoogleCloudPlatform/community#770]
Hi, 

I think it's better for this tutorial not to deploy to app engine flex environment since it's not free. Standard environment should do. 

Kind regards, 
Tomy Jaya

**Comment by ToddKopriva** [comment]
@ideafest , I'm tagging you so that you see this suggestion about a tutorial that you authored.

**Comment by ideafest** [comment]
> Hi,
> 
> I think it's better for this tutorial not to deploy to app engine flex environment since it's not free. Standard environment should do.
> 
> Kind regards,
> Tomy Jaya

Hey Tomy,

Thank you for feedback.  App engine Standard is [not free](https://cloud.google.com/appengine/pricing#standard_instance_pricing). There is a [great documentation](https://cloud.google.com/appengine/docs/the-appengine-environments) on choosing right environment for running your application. Ideally best way to improve this application is to run it in a container so that you can run it either on cloud (e.g. GKE, App engine Flex) or onprem.

Feel free to reach out in case of any further questions.

Thank you!

**Comment by ToddKopriva** [comment]
Thanks for the response.

Tomy, I'm going to go ahead and close this issue, since there doesn't seem to be a direct issue with the tutorial, but feel free to continue the conversation.
