### ISSUE TITLE
Cloud function while trigger - testing error

### ISSUE THREAD

**Issue by pratikdhavale** [GoogleCloudPlatform/community#889]
Getting output while testing the function

stopInstancePubSub
u3sbsgzeovt3
TypeError: callback is not a function at exports.stopInstancePubSub (/srv/functions/index.js:53:5) at Promise.resolve.then (/srv/node_modules/@google-cloud/functions-framework/build/src/invoker.js:330:28) at process._tickCallback (internal/process/next_tick.js:68:7)

Referring the doc/code from here: [https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule](url)

**Comment by ToddKopriva** [comment]
@pratikdhavale , thanks for reporting this problem. Because the problem that you're having is not with code in this repository, I'm going to close this issue.

Please use the "Send feedback" button in the upper-right corner of the page where the issue occurs to report the problem:
https://cloud.google.com/scheduler/docs/start-and-stop-compute-engine-instances-on-a-schedule

If I'm misunderstanding your issue, let please let me know.
