### ISSUE TITLE
Issue pulling private images using docker-compose container on container optimized os 

### ISSUE THREAD

**Issue by jwtea** [GoogleCloudPlatform/community#942]
Not sure if this is the correct place to ask but following this [article](https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os) 
the docker-compose container is not authed with GCP to access private images.

`unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication`

Hoping someone could shed some light on how to pass the host auth to this container / or how to auth the container with GCP / is this possible.

Thanks in advance

**Comment by ToddKopriva** [comment]
@tswast , I'm tagging you so that you can see this question about a tutorial that you submitted.

@jwtea , the Issues section of this GitHub repository is generally not the best place to get questions answered. I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

That said, I'll leave this issue open in case @tswast can address it here.

**Comment by tswast** [comment]
+1 to Todd's comment that GitHub isn't the best place for this question.

That said, I believe the gist of what's needed is:

1. Check which service account it being used for the GCE instance.
2. Make sure that service account has object viewer GCS permissions on the bucket that GCR uses for private images.

**Comment by ToddKopriva** [comment]
Thanks, Tim.
