### ISSUE TITLE
Issue with cloud-iot-gateways-rpi

### ISSUE THREAD

**Issue by RajinTech** [GoogleCloudPlatform/community#960]
➜  cloud-iot-gateways-rpi git:(master) ✗ source run-gateway
Traceback (most recent call last):
  File "./cloudiot_mqtt_gateway.py", line 22, in <module>
    import jwt
ImportError: No module named jwt

When running source run-gateway it says there is no module named jwt

**Comment by ToddKopriva** [comment]
@hongalex , I'm tagging you so that you can see this issue reported against a tutorial that you submitted.

**Comment by hongalex** [comment]
Hey @RajinTech, thanks for bringing this up.

Have you run the `pip install` step to install the jwt library? If so, what kind of device are you using as your gateway?

**Comment by RajinTech** [comment]
Hi @hongalex I ran pip3 install -r requirements-gateway.txt for the install step. Im using a macbook with Mojave

**Comment by RajinTech** [comment]
`➜  cloud-iot-gateways-rpi git:(master) ✗ pip3 install -r requirements-gateway.txt
Requirement already satisfied: cryptography==2.4.1 in /usr/local/lib/python3.7/site-packages (from -r requirements-gateway.txt (line 1)) (2.4.1)
Requirement already satisfied: paho-mqtt in /usr/local/lib/python3.7/site-packages (from -r requirements-gateway.txt (line 2)) (1.4.0)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.7/site-packages (from -r requirements-gateway.txt (line 3)) (1.6.4)
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python3.7/site-packages (from cryptography==2.4.1->-r requirements-gateway.txt (line 1)) (2.8)
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python3.7/site-packages (from cryptography==2.4.1->-r requirements-gateway.txt (line 1)) (0.24.0)
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python3.7/site-packages (from cryptography==2.4.1->-r requirements-gateway.txt (line 1)) (1.12.0)
Requirement already satisfied: cffi!=1.11.3,>=1.7 in /usr/local/lib/python3.7/site-packages (from cryptography==2.4.1->-r requirements-gateway.txt (line 1)) (1.12.3)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.7->cryptography==2.4.1->-r requirements-gateway.txt (line 1)) (2.19)`

**Comment by hongalex** [comment]
Ah gotcha. This article was written using python 2, so that might be the first point of contention. I also recommend installing/running the gateway code inside a virtual environment. Some instructions on how to set that up can be found here: https://github.com/GoogleCloudPlatform/community/issues/954#issuecomment-511953666

I'll be updating the tutorial to first include more detailed info on how to setup the virtual environment, and eventually migrate it over to python 3.

**Comment by ToddKopriva** [comment]
Thanks for following up, Alex.

**Comment by ToddKopriva** [comment]
It seems that Alex's PR #962 deals with this issue, so I'm closing this issue report.

If you find that this issue isn't resolved, re-open the issues and let us know.

**Comment by RajinTech** [comment]
@hongalex Thanks for the update I will try that. I'm having a hard time wrapping my head around the purpose of the virtual environment. Sounds like it creates a space to have a different version of python running? I am using this for an industrial automation project so I am going to be using a dedicated pi for the device and another for the gateway. Does that mean that every time I turn my gateway pi on I have to run the "source run-gateway" command?

**Comment by hongalex** [comment]
Generally a [virtual environment](https://virtualenv.pypa.io/en/stable/userguide) is for creating an isolated workspace to install Python packages. It does still depend on a python version that you already have on your base machine, but it provides the benefit of isolating packages to a specific project from say the base system's python packages.

Looking back at your issue, it probably could've been resolved by running `pip install -r requirements-gateway.txt` using a version of pip that matches python 2.7 instead, rather than `pip3`. If you take a look into the `run-gateway` file, the command uses just `python` which defaults to `python 2.7` on macOS I believe.

To answer your other question, yes the `run-gateway` script would need to be run on startup. If this is a dedicated device, you could probably put that command into a startup script that runs in the background.

Hope that helps!
