### ISSUE TITLE
 Mender google IOT setup produces ERROR: (gcloud.iot.devices.create) INVALID_ARGUMENT: The format of 'device.id' is invalid

### ISSUE THREAD

**Issue by bulbage** [GoogleCloudPlatform/community#969]
Hello,
I am following this IOT example:
https://cloud.google.com/community/tutorials/cloud-iot-mender-ota

When I execute this line:
gcloud iot devices create $DEVICE_ID --region=$CLOUD_REGION --project $PROJECT --registry=$REGISTRY_ID --public-key path=rsa_public.pem,type=RSA_PEM

I receive:
ERROR: (gcloud.iot.devices.create) INVALID_ARGUMENT: The format of 'device.id' is invalid:

$DEVICE_ID: for my device is MAC address of the device = xx:xx:xx:xx:xx:xx
According to this document the ID can be MAC address. I tried taking out ":" but same results.

There is no specific format specification in the google documentation for this command.
Any help would be much appreciated.

Thanks you.

**Comment by ToddKopriva** [comment]
@Kcr19 , I'm tagging you so that you can see this issue report about a tutorial that you submitted.

@bulbage , the Issues section of this GitHub repository is not the best place to get such questions answered quickly.

I recommend bringing your question to one of the forums described here:
https://cloud.google.com/support/docs/community

Many members of the GCP community---including Google employees and other experts---help out on those forums.

**Comment by bulbage** [comment]
@ToddKopriva Thank you for the prompt reply. I will post it there.
